### ISSUE TITLE
Update Article 22 - ending membership if subscription payments lapse

### ISSUE THREAD

**Issue by Hibby** [hackerdeen/articles#1]
Update Article 22, currently reading:

> If the membership subscription payable by any member remains
  outstanding more than 2 months after the date on which it fell due -
  and providing he/she has been given at least one reminder (either in
  writing or by e-mail) - the board may, by resolution to that effect,
  expel him/her from membership.

To include a 12 month time limit for outstanding payment, and after 12 months they are considered Automatically dismembered.

>If the membership subscription payable by any member remains
  outstanding more than 2 months after the date on which it fell due -
  and providing he/she has been given at least one reminder (either in
  writing or by e-mail) - the board may, by resolution to that effect,
  expel him/her from membership. If, 12 months after the date on which
  an outstanding payment fell due it has not been paid, the member shall
  be expelled from membership.

**Comment by AndyGaskell** [comment]
The work by @Nick0o in the PR 2023 AGM Proposal https://github.com/hackerdeen/articles/pull/6 covers this.

**Comment by AndyGaskell** [comment]
Passed at the AGM, see https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md

PR merged.
