### ISSUE TITLE
Propose membership secretary

### ISSUE THREAD

**Issue by Hibby** [hackerdeen/articles#2]
In a manner similar to Treasurer in Article 60, 61:

> One of the directors shall be the treasurer

I propose we have a director responsible for membership issues - applications, dismemberment, maintaining the register of members and other tasks the directors may find appropriate

**Comment by irl** [comment]
The register of members is a statutory register so we should be careful how we’re wording this change. The legal responsibility for the proper keeping of the register falls to all officers of the company.

**Comment by AndyGaskell** [comment]
Re @irl comment there...

> The register of members is a statutory register so we should be careful how we’re wording this change. The legal responsibility for the proper keeping of the register falls to all officers of the company.

...yea, we could say something like...

> One of the directors shall be delegated responsibility to administer membership, this person shall be labelled 'membership secretary'.

**Comment by AndyGaskell** [comment]
The work by @Nick0o in the PR 2023 AGM Proposal https://github.com/hackerdeen/articles/pull/6 covers this.

**Comment by AndyGaskell** [comment]
Not passed at the AGM, see https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md
