### ISSUE TITLE
Change artcles so the AGM doesn't have to be in April

### ISSUE THREAD

**Issue by AndyGaskell** [hackerdeen/articles#3]
It would be good to change it so that we can have an AGM in months other than April.  Currently it says...

`33 The board must arrange a meeting of members (an annual general meeting or “AGM”) in the month of April each calendar year.`

...we could change it to...

`33 The board must arrange a meeting of members (an annual general meeting or “AGM”) each calendar year.`

...so just removing the 'in the month of April' bit.

**Comment by irl** [comment]
We could go for "at least every 18 months and at most every 9 months". Gives us some room.

Companies Act no longer requires an AGM so this is just a thing we made up in the articles as far as the law is concerned, we can do it on the timescale of our choosing.

**Comment by AndyGaskell** [comment]
Yea, that'd be fine too.

We could call it a WGM, short for Whenever General Meeting, since it'd not necessarily be annual 😀

Either way, I think as long as it's not tied to being in April.

**Comment by AndyGaskell** [comment]
The work by @Nick0o in the PR 2023 AGM Proposal https://github.com/hackerdeen/articles/pull/6 covers this.

**Comment by AndyGaskell** [comment]
The reason for is being April was, I think, so it is the month after the financial year end.

**Comment by AndyGaskell** [comment]
Passed at the AGM, see https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md

PR merged.
