### ISSUE TITLE
Remove binary pronouns from articles

### ISSUE THREAD

**Issue by irl** [hackerdeen/articles#5]
While it's nice that we are progressive enough to have included non-males in the articles with our liberal use of "he/she", we could just take the next step and remove the use of pronouns entirely. I propose we instead refer to "the member", "the director", etc. as terms defined in the articles. This removes ambiguity while also making the space more inclusive.

**Comment by AndyGaskell** [comment]
The work by @Nick0o in the PR 2023 AGM Proposal #6 covers this.

**Comment by AndyGaskell** [comment]
Passed at the AGM, see https://github.com/hackerdeen/meetings/blob/master/2023/2023-04-04_AGM_Minutes.md

PR merged.
